package delta.leo.binding;

/**
 * Standard binding properties names.
 * @author DAM
 */
public class BindingPropertyNames
{
  /**
   * "PRELOAD" binding property.<p>
   * A preloaded field is always loaded when the object is first loaded from data location.
   */
  public static final String PRELOAD="PRELOAD";
  /**
   * "AUTOGENERATED" field property.<p>
   * An autogenerated field has its value automatically generated by the data location when the parent object is created.
   */
  public static final String AUTOGENERATED="AUTOGENERATED";
}
